apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node-image
spec:
  type: NodePort
  ports:
  - port: 3000
  selector:
    app: node-image
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-image
  labels:
    app: node
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: dossaan/node-api-image:latest
        ports:
        - containerPort: 3000
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 200
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 200
          periodSeconds: 10